import Config

# Configure your database
config :estest, Estest.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "estest_dev",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :estest, EstestWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "xTKG6ES+9WrBLIpcnr2XZ3Q7p/SyEsa7FcUilkwdPAQjglCbUQ/L+Cdy2ZWCwjKQ",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :estest, Estest.ElasticsearchCluster,
  url: "http://localhost:9200",
  username: "elastic",
  password: "lbuzf+wn2khA6-c68WI+",
  api: Elasticsearch.API.HTTP,
  json_library: Jason,
  indexes: %{
    products: %{
      settings: "priv/elasticsearch/products.json",
      store: Estest.ElasticsearchStore,
      sources: [Estest.Products.Product],
      bulk_page_size: 5_000,
      bulk_wait_interval: 15_000,
      bulk_action: "create"
    }
  }
